using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CPU_Profile_Display
{
    public enum CPUProps {
            AddressWidth,
            Architecture,
            AssetTag,
            Availability,
            Caption,
            Characteristics,
            ConfigManagerErrorCode,
            ConfigManagerUserConfig,
            CpuStatus,
            CreationClassName,
            CurrentClockSpeed,
            CurrentVoltage,
            DataWidth,
            Description,
            DeviceID,
            ErrorCleared,
            ErrorDescription,
            ExtClock,
            Family,
            InstallDate,
            L2CacheSize,
            L2CacheSpeed,
            L3CacheSize,
            L3CacheSpeed,
            LastErrorCode,
            Level,
            LoadPercentage,
            Manufacturer,
            MaxClockSpeed,
            Name,
            NumberOfCores,
            NumberOfEnabledCore,
            NumberOfLogicalProcessors,
            OtherFamilyDescription,
            PartNumber,
            PNPDeviceID,
            PowerManagementCapabilities,
            PowerManagementSupported,
            ProcessorId,
            ProcessorType,
            Revision,
            Role,
            SecondLevelAddressTranslationExtensions,
            SerialNumber,
            SocketDesignation,
            Status,
            StatusInfo,
            Stepping,
            SystemCreationClassName,
            SystemName,
            ThreadCount,
            UniqueId,
            UpgradeMethod,
            Version,
            VirtualizationFirmwareEnabled,
            VMMonitorModeExtensions,
            VoltageCaps
        };    
}
